# Generated by Django 5.2 on 2025-06-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customerdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
